# Generated by Django 5.0.3 on 2024-04-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('is_client', models.BooleanField(default=False, verbose_name='клиент')),
                ('is_trainer', models.BooleanField(default=False, verbose_name='тренер')),
                ('is_admin', models.BooleanField(default=False, verbose_name='админ')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='спортзал')),
                ('address', models.CharField(max_length=100, verbose_name='адресс')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FitnessTrainer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fit.customuser', verbose_name='фитнесс-тренер')),
                ('full_name', models.CharField(max_length=200, verbose_name='полное имя')),
                ('date_of_birth', models.DateField(verbose_name='дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='пол')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='фото профиля')),
                ('gyms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='fit.gym', verbose_name='спортзалы')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20, verbose_name='день недели')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('end_time', models.TimeField(verbose_name='конец')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.gym', verbose_name='спортзал')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fit.fitnesstrainer', verbose_name='расписание тренеров')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписании',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='дата тренировки')),
                ('appointment_time', models.TimeField(verbose_name='время тренировки')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10, verbose_name='статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='fit.customuser', verbose_name='клиент')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.schedule', verbose_name='расписание')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.fitnesstrainer', verbose_name='тренер')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['-id'],
            },
        ),
    ]
