# Generated by Django 5.0.3 on 2024-04-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitnesstrainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренера'},
        ),
    ]
