# Generated by Django 5.0.3 on 2024-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0006_alter_fitnesstrainer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstrainer',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile_images/default_profile.jpg', null=True, upload_to='profile_images/', verbose_name='фото профиля'),
        ),
    ]
